---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mygo-instance-1
  name: mygo-dev
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "pods"]
  verbs: ["get", "list", "watch"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metadata:
  name: mygo-dev-bind
  namespace: mygo-instance-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mygo-dev
subjects:
- kind: ServiceAccount
  name: mygo-dev
  namespace: default
  
  
##### END ROLE1 #####


### ROLE2 ###
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mygo-instance-1
  name: mygo-dev
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["", "apps", "extensions"]
  resources: ["deployments", "configmaps", "services", "endpoints", "pods", "pods/log", "pods/exec", "replicasets", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mygo-dev-bind
  namespace: mygo-instance-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mygo-dev
subjects:
- kind: ServiceAccount
  name: mygo-dev
  namespace: default

##### END ROLE2 #####